# Generated by Django 5.2.6 on 2026-01-16 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('question_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('domain', models.CharField(choices=[('reading', 'Reading'), ('writing', 'Writing'), ('math', 'Math'), ('attention', 'Attention')], max_length=20)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], max_length=20)),
                ('question_text', models.TextField()),
                ('options', models.JSONField()),
                ('correct_option', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'questions',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('age_group', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('session_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='assessment.user')),
            ],
            options={
                'db_table': 'sessions',
            },
        ),
        migrations.CreateModel(
            name='FinalPrediction',
            fields=[
                ('prediction_id', models.AutoField(primary_key=True, serialize=False)),
                ('dyslexia_risk_score', models.FloatField()),
                ('dyscalculia_risk_score', models.FloatField()),
                ('attention_risk_score', models.FloatField()),
                ('final_label', models.CharField(max_length=100)),
                ('key_insights', models.JSONField(blank=True, null=True)),
                ('confidence_level', models.CharField(default='moderate', max_length=20)),
                ('predicted_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='assessment.session')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='assessment.user')),
            ],
            options={
                'db_table': 'final_predictions',
            },
        ),
        migrations.CreateModel(
            name='UserResponse',
            fields=[
                ('response_id', models.AutoField(primary_key=True, serialize=False)),
                ('domain', models.CharField(max_length=20)),
                ('difficulty', models.CharField(max_length=20)),
                ('correct', models.BooleanField()),
                ('response_time_ms', models.IntegerField()),
                ('confidence', models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=20, null=True)),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='assessment.question')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='assessment.session')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='assessment.user')),
            ],
            options={
                'db_table': 'user_responses',
            },
        ),
        migrations.CreateModel(
            name='MistakePattern',
            fields=[
                ('mistake_id', models.AutoField(primary_key=True, serialize=False)),
                ('mistake_type', models.CharField(max_length=100)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=20)),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mistakes', to='assessment.userresponse')),
            ],
            options={
                'db_table': 'mistake_patterns',
            },
        ),
    ]
